In [183]:
import pandas as pd
file=pd.read_excel('Olympic 2012 Medal Tally.xlsx')
print(file)

   Unnamed: 0     Unnamed: 1    Unnamed: 2 Unnamed: 3   Unnamed: 4 Unnamed: 5  \
0         NaN        Country  Country Code       Year  Medal Tally        NaN   
1         NaN            NaN           NaN        NaN         Gold     Silver   
2         NaN  Great Britain           GBR       2012           29         17   
3         NaN         China            CHN       2012           38         28   
4         NaN         Russia           RUS       2012           24         25   
5         NaN  United States            US       2012           46         28   
6         NaN          Korea           KOR       2012           13          8   
7         NaN          Japan           JPN       2012            7         14   
8         NaN        Germany           GER       2012           11         11   

  Unnamed: 6  
0        NaN  
1     Bronze  
2         19  
3         22  
4         32  
5         29  
6          7  
7         17  
8         14  


In [156]:
import numpy as np
file_country=file.loc[:,"Unnamed: 1"][2:]
file_country_array=np.array(file_country)
file_country_array

array(['Great Britain', 'China ', 'Russia', 'United States', 'Korea',
       'Japan', 'Germany'], dtype=object)

In [174]:
file_country_gold=file.loc[:,"Unnamed: 4"][2:]
file_country_gold_array=np.array(file_country_gold)
print(file_country_gold_array)

[29 38 24 46 13 7 11]


In [159]:
file_country_silver=file.loc[:,"Unnamed: 5"][2:]
file_country_silver_array=np.array(file_country_silver)
file_country_silver_array

array([17, 28, 25, 28, 8, 14, 11], dtype=object)

In [160]:
file_country_bronze=file.loc[:,"Unnamed: 6"][2:]
file_country_bronze_array=np.array(file_country_bronze)
file_country_bronze_array

array([19, 22, 32, 29, 7, 17, 14], dtype=object)

In [168]:
highest_goldmadel_index=file_country_gold_array.argmax()
highest_goldmadel_country=file_country_array[highest_goldmadel_index]
print(highest_goldmadel_country)

United States


In [173]:
madel_won_greater_20=file_country_gold_array>20
more20_goldmadel_country=file_country_array[madel_won_greater_20]
print(more20_goldmadel_country)

['Great Britain' 'China ' 'Russia' 'United States']


In [177]:
print("Gold Madel"+str(file_country_gold_array))
print("Silver Madel"+str(file_country_silver_array))
print("Bronze Madel"+str(file_country_bronze_array))

Gold Madel[29 38 24 46 13 7 11]
Silver Madel[17 28 25 28 8 14 11]
Bronze Madel[19 22 32 29 7 17 14]


In [180]:
for i in range(len(file_country_array)):
    print("Country "+str(file_country_array[i])+" has won "+str(file_country_gold_array[i])+" gold madel")

Country Great Britain has won 29 gold madel
Country China  has won 38 gold madel
Country Russia has won 24 gold madel
Country United States has won 46 gold madel
Country Korea has won 13 gold madel
Country Japan has won 7 gold madel
Country Germany has won 11 gold madel


In [182]:
for i in range(len(file_country_array)):
    print("Country "+str(file_country_array[i])+" has won "+str(file_country_gold_array[i]+file_country_silver_array[i]+file_country_bronze_array[i])+" total madel")

Country Great Britain has won 65 total madel
Country China  has won 88 total madel
Country Russia has won 81 total madel
Country United States has won 103 total madel
Country Korea has won 28 total madel
Country Japan has won 38 total madel
Country Germany has won 36 total madel
